# Generated by Django 4.2 on 2023-05-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=20, null=True)),
                ('Email', models.EmailField(max_length=20, null=True)),
                ('Subject', models.TextField(max_length=30, null=True)),
                ('Message', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
