# Generated by Django 4.2 on 2023-05-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.TextField(max_length=20, null=True)),
                ('LastName', models.TextField(max_length=20, null=True)),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not Specified', 'Not Specified')], default='Male', max_length=20)),
                ('City', models.TextField(max_length=20, null=True)),
                ('State', models.TextField(max_length=20, null=True)),
                ('Address', models.TextField(max_length=20, null=True)),
                ('AadharNumber', models.TextField(max_length=20, null=True)),
                ('BloodGroup', models.TextField(max_length=20, null=True)),
                ('BodyWeight', models.IntegerField()),
                ('Covid', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20)),
                ('DISEASES', models.TextField(blank=True, max_length=20, null=True)),
                ('Verification', models.FileField(blank=True, upload_to='None')),
            ],
        ),
    ]
