# Generated by Django 4.2 on 2023-05-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='Phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
