# Generated by Django 4.2 on 2023-05-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_registration_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Address',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
